### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#130]
### Intro

As the first out of five issues this one will be a bit longer and will have some technical information besides screenshots themselves. 

[Figma Source](https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase?type=design&node-id=3291%3A68596&mode=design&t=oZhs4hIMd1ft8Tab-1)

a. Vertical spacings. 60/50 on desktops, 40/30 on mobile. Higher values are meant for top and bottom, lower values for space between content. There are exceptions in places where textual, or where needed.
b. Starry theme. Ideally implemented as svg/vector, so it doesn't pixelate.
c. Frame of the website thumbnail. Ideally scales proportionally in its own container/column that can be aligned to any text below (with left and right edge). If you check its values on various sizes, you'll see it is resized proportionally (decimals). If discussion needed, just ping and we can huddle.
d. Screenshots. [Taken in 4k, feel free to resize.](https://drive.google.com/drive/folders/13z0vaiGxp4Es9q1PPi5rHenX94AQrLjl?usp=drive_link) These are raw, while those in Figma are positioned manually. Let me know if you want me to cut and trim these to precise size, or you can do so by following Figma examples. This is manually only for Landing page sites, all other sites could be processed automatically.
e. [Hero section.](https://github.com/WordPress/wporg-showcase-2022/assets/111751264/da0d698b-ca7b-47bc-ab95-0dc9ddfd6cab) Hero section's website should change with each visit. These sites aren't final, but we don't have better ones from the available list. I'll ask Jonathan Pantani to provide some alternatives if these cannot go.

**Important — will be done in parallel.**
- [ ] Filters aren't done, they are in progress.
- [x] Hover states are yet to be made.
- [ ] Website tags aren't done, they are to be delivered by Stargate, with content.
- [x] Website copy edits.
- [ ] Francisco is making all pages with variables and components, so you can have dev preview in Figma as well. 
- [x] Landing Hero sites selection.
- [x] Site Thumbnails. Cut screenshots to exact ratio as variable made component.

<table>
<thead>
<tr>
<th>Small screen</th>
<th>Medium</th>
<th>Large screen</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><img alt="small" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/6bece7a2-aa6d-43cb-8926-e3bf7535c2f5" /></td>
<td valign="top"><img alt="med" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/4dd51d7b-4baa-4e9d-ad82-6353ed8bfafa" /></td>
<td valign="top"><img alt="large" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/00efda50-44e4-4e51-86c8-431a579ee31d" /></td>
</tr>
</tbody>
</table>

Content max width: 1760 + padding 80: [Monitor Extra Large](https://github.com/WordPress/wporg-showcase-2022/assets/111751264/81097586-a035-4c26-a250-3df6b6586473)

**Comment by marko-srb** [comment]
Updated to-do's above. Each will be checked as soon as is done. Three of the major ones should be completed today.

**Comment by marko-srb** [comment]
Updates:

- Copy is final in [this Figma file](https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase?type=design&node-id=3291%3A68596&mode=design&t=Bh5CjgjYWdPbUmhk-1). Provided by Stargate.
- Sites selection is final. Approved by Stargate. Added cropped desktop screenshots, in [the same folder](https://drive.google.com/drive/folders/13z0vaiGxp4Es9q1PPi5rHenX94AQrLjl?usp=drive_link).
- Focus and hover states are [added to the main component](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=2356-10317&mode=design&t=QbXhW1CbMG2m4FYY-4), yet to be added in the designs, but you can use them there if you need to.
- Variables. There are a few challenges that Francisco aims to tackle (which impact several things in systematic approach). He is aiming to work on these next week and we hope to have them for you then, if anything changes we'll let you know.

Other than that I think everything is done, except the filters (which is a longer game). Let us know if you need anything else...

CC: @WordPress/meta-design

**Comment by ryelle** [comment]
Tracking the Homepage work:

- [ ] Local nav bar
- [ ] Hero section, PR in #145 
- [ ] Filters, TBD pending feedback see https://github.com/WordPress/wporg-mu-plugins/issues/419
- [x] Site grid of featured items #136
- [x] View all & dots
- [x] Local footer content

**Comment by jasmussen** [comment]
Thanks for the effort! Just wanted to note that we can remove the "TBD" on the filter-bar.

**Comment by ryelle** [comment]
All aspects of the homepage have been completed. New issues can be created for any feedback or fixes.
