### ISSUE TITLE
Design Audit Tasks

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#59]
#### [Design team feedback threads](https://nesosoup.wordpress.com/2022/11/22/showcase-redesign-quick-update-2/#comment-2293)

**Tasks**
- [x] Round images to `2px` if not full width
- [x] Round Single site meta details 
- [x] Left align Submit section, do same for .org homepage (https://github.com/WordPress/wporg-showcase-2022/pull/60)
- [x] Expand content width to match designs
- [x] Reduce Size of subnav text
- [x] Remove paint brush stroke to sub-nav -- Owner: @REN
- [ ] Fix fluid alignment of content & surrounding components (https://github.com/WordPress/wporg-showcase-2022/issues/62)
- [x] Reduce pagination link size.

**Comment by StevenDufresne** [comment]
Closing as the last item remaining is logged as a separate issue.
